env:
  RUBY_VERSION: 3.0.0
  TEST_DB: eventy_test
  TEST_USER: postgres
  TEST_PASSWORD: postgres
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

name: Rails Specs
on: [push, pull_request]
jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-latest
    container:
      image: ruby:3.0.0
    services:
      postgres:
        image: postgres:latest
        ports:
        - 5432:5432
        env:
          POSTGRES_USER: ${{ env.TEST_USER }}
          POSTGRES_PASSWORD: ${{ env.TEST_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Gem cache
        id: cache-bundle
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}
      - name: Copy DB Config
        run: cp config/database.yml.ci config/database.yml
      - name: Setup DB
        run: |
          bin/rails db:create db:schema:load RAILS_ENV=test
      - name: Run tests
        run: bundler exec rspec
      - name: Upload coverage results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage-report
          path: coverage
